CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 display_name VARCHAR(120) DEFAULT NULL,
 role ENUM('user','admin') NOT NULL DEFAULT 'user',
 status ENUM('active','suspended') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profiles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 username VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(120) DEFAULT NULL,
 bio VARCHAR(300) DEFAULT NULL,
 avatar_url VARCHAR(500) DEFAULT NULL,
 theme VARCHAR(40) NOT NULL DEFAULT 'default',
 status ENUM('active','disabled') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED DEFAULT NULL,
 short_code VARCHAR(32) NOT NULL UNIQUE,
 destination_url TEXT NOT NULL,
 is_custom TINYINT(1) NOT NULL DEFAULT 0,
 is_anonymous TINYINT(1) NOT NULL DEFAULT 1,
 status ENUM('active','disabled','expired') NOT NULL DEFAULT 'active',
 click_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
 expires_at DATETIME DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_user_id (user_id),
 INDEX idx_status (status),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profile_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 profile_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(120) NOT NULL,
 url TEXT NOT NULL,
 icon VARCHAR(50) DEFAULT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 status ENUM('active','disabled') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
 INDEX idx_profile_order (profile_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clicks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 link_id BIGINT UNSIGNED NOT NULL,
 clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ip_hash CHAR(64) DEFAULT NULL,
 referrer VARCHAR(1000) DEFAULT NULL,
 user_agent VARCHAR(500) DEFAULT NULL,
 FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE,
 INDEX idx_link_time (link_id, clicked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 link_id BIGINT UNSIGNED DEFAULT NULL,
 email VARCHAR(190) DEFAULT NULL,
 reason VARCHAR(120) NOT NULL,
 message TEXT,
 status ENUM('open','reviewed','closed') NOT NULL DEFAULT 'open',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blocked_domains (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 domain VARCHAR(255) NOT NULL UNIQUE,
 reason VARCHAR(255) DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
 setting_key VARCHAR(100) PRIMARY KEY,
 setting_value TEXT,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
